version: '3'

volumes:
  pg_data:
  pdf:
  media:
  static:

services:
  
  redis:
    image: redis:alpine
  
  db:
    image: postgres:16.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  backend:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media/covers
    ports:
      - 8000:8000

  celery_worker:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      - redis
      - backend
    command: celery -A backend worker -l info
    volumes:
      - media:/app/media/covers

  celery_beat:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      - celery_worker
    command: celery -A backend beat -l info
    volumes:
      - media:/app/media/covers