# Generated by Django 5.0.2 on 2024-02-29 13:07

import django.core.validators
import django.db.models.deletion
import payment.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('invisible', models.BooleanField(default=False)),
                ('first_name_user', models.CharField(max_length=150)),
                ('last_name_user', models.CharField(max_length=150)),
                ('email_user', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount_to_collect', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_collected', models.PositiveIntegerField(default=0)),
                ('amount_of_people_donated', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='covers/', validators=[payment.validators.validate_file_size])),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.collect')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.payment')),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='payments',
            field=models.ManyToManyField(related_name='collections', through='payment.CollectPayment', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='collect',
            name='reasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='payment.reason'),
        ),
    ]
