# Generated by Django 5.0.2 on 2024-02-29 14:32

import django.core.validators
import payment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование сбора')),
                ('description', models.TextField(verbose_name='Описание сбора')),
                ('amount_to_collect', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько надо собрать')),
                ('amount_collected', models.PositiveIntegerField(default=0, verbose_name='Уже собрано')),
                ('amount_of_people_donated', models.PositiveIntegerField(default=0, verbose_name='Количество людей, отправивших платеж')),
                ('cover_image', models.ImageField(upload_to='covers/', validators=[payment.validators.validate_file_size], verbose_name='Обложка-изображение сбора')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала сбора')),
            ],
            options={
                'verbose_name': 'Групповой сбор',
                'verbose_name_plural': 'Групповые сборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Групповой сбор и платеж',
                'verbose_name_plural': 'Групповые сборы и платежи',
                'ordering': ['-collect', 'payment'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма платежа в рублях')),
                ('donated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления платежа')),
                ('invisible', models.BooleanField(default=False, verbose_name='Скрыта ли сумма платежа')),
                ('first_name_user', models.CharField(max_length=150, verbose_name='Имя пользователя, сделавшего платеж')),
                ('last_name_user', models.CharField(max_length=150, verbose_name='Фамилия пользователя, сделавшего платеж')),
                ('email_user', models.EmailField(max_length=254, verbose_name='Email пользователя, сделавшего платеж')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Наименование причины сбора')),
            ],
            options={
                'verbose_name': 'Причина для сбора',
                'verbose_name_plural': 'Причины для сбора',
                'ordering': ['title'],
            },
        ),
    ]
