# Generated by Django 5.0.2 on 2024-02-27 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount_to_collect', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_collected', models.PositiveIntegerField(default=0)),
                ('anount_of_people_donated', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('invisible', models.BooleanField(default=False)),
                ('first_name_user', models.CharField(max_length=150)),
                ('last_name_user', models.CharField(max_length=150)),
                ('middle_name_user', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
    ]
