# Generated by Django 5.0.2 on 2024-02-29 13:30

import django.core.validators
import django.db.models.deletion
import payment.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Групповой сбор', 'verbose_name_plural': 'Групповые сборы'},
        ),
        migrations.AlterModelOptions(
            name='collectpayment',
            options={'ordering': ['-collect', 'payment'], 'verbose_name': 'Групповой сбор и платеж', 'verbose_name_plural': 'Групповые сборы и платежи'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-donated_at'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['title'], 'verbose_name': 'Причина для сбора', 'verbose_name_plural': 'Причины для сбора'},
        ),
        migrations.AlterField(
            model_name='collect',
            name='amount_collected',
            field=models.PositiveIntegerField(default=0, verbose_name='Уже собрано'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='amount_of_people_donated',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество людей, отправивших платеж'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='amount_to_collect',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько надо собрать'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='cover_image',
            field=models.ImageField(upload_to='covers/', validators=[payment.validators.validate_file_size], verbose_name='Обложка-изображение сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='description',
            field=models.TextField(verbose_name='Описание сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='Дата и время окончания сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='payments',
            field=models.ManyToManyField(related_name='collections', through='payment.CollectPayment', to='payment.payment', verbose_name='Платежи пользователей'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='reasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='payment.reason', verbose_name='Причина сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование сбора'),
        ),
        migrations.AlterField(
            model_name='collectpayment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.collect', verbose_name='Групповой сбор'),
        ),
        migrations.AlterField(
            model_name='collectpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.payment', verbose_name='Платеж пользователя'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма платежа в рублях'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='donated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email_user',
            field=models.EmailField(max_length=254, verbose_name='Email пользователя, сделавшего платеж'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_name_user',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя, сделавшего платеж'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invisible',
            field=models.BooleanField(default=False, verbose_name='Скрыта ли сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name_user',
            field=models.CharField(max_length=150, verbose_name='Фамилия пользователя, сделавшего платеж'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Наименование причины сбора'),
        ),
    ]
