# Generated by Django 5.0.2 on 2024-02-29 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора'),
        ),
        migrations.AddField(
            model_name='collectpayment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.collect', verbose_name='Групповой сбор'),
        ),
        migrations.AddField(
            model_name='collectpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_payments', to='payment.payment', verbose_name='Платеж пользователя'),
        ),
        migrations.AddField(
            model_name='collect',
            name='payments',
            field=models.ManyToManyField(related_name='collections', through='payment.CollectPayment', to='payment.payment', verbose_name='Платежи пользователей'),
        ),
        migrations.AddField(
            model_name='collect',
            name='reasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='payment.reason', verbose_name='Причина сбора'),
        ),
    ]
