# Generated by Django 5.0.2 on 2024-02-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectpayment',
            old_name='Payment',
            new_name='payment',
        ),
    ]
