# Generated by Django 5.0.2 on 2024-02-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='surname_user',
        ),
    ]
