# Generated by Django 5.0.2 on 2024-02-27 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_payment_collectpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
