# Generated by Django 5.0.2 on 2024-02-27 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_reason_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
