# Generated by Django 5.0.2 on 2024-02-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_reason_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='anount_of_people_donated',
            new_name='amount_of_people_donated',
        ),
    ]
